services:
  webserver:
    image: nginx:latest
    container_name: webserver
    tty: true
    ports:
      - "8080:80"
      - "8081:8081"
    volumes:
      - ./tanrise_admin:/var/www/tanrise_admin
      - ./tanrise_api:/var/www/tanrise_api
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webapp
      - restapi
    networks:
      - app-network

  webapp:
    build:
      context: ./tanrise_admin
      dockerfile: Dockerfile
    container_name: webapp
    tty: true
    volumes:
      - ./tanrise_admin:/var/www/tanrise_admin
    env_file:
      - tanrise_admin/.env.docker
    command: sh -c "composer install --no-interaction --no-dev --prefer-dist && php-fpm"
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  restapi:
    build:
      context: ./tanrise_api
      dockerfile: Dockerfile
    container_name: restapi
    tty: true
    volumes:
      - ./tanrise_api:/var/www/tanrise_api
    env_file:
      - tanrise_api/.env.docker
    command: sh -c "composer install --no-interaction --no-dev --prefer-dist && php-fpm"
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
