services:
  webserver:
    image: nginx:latest
    container_name: webserver
    tty: true
    ports:
      - '8080:80'
    volumes:
      - ./tanrise_admin:/var/www/tanrise_admin
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webapp
    networks:
      - app-network

  webapp:
    build:
      context: ./tanrise_admin
      dockerfile: Dockerfile
    container_name: webapp
    tty: true
    volumes:
      - ./tanrise_admin:/var/www/tanrise_admin
    env_file:
      - tanrise_admin/.env
    command: sh -c "composer install --no-interaction --no-dev --prefer-dist && php-fpm"
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge